-- MySQL Script generated by MySQL Workbench
-- 01/02/17 22:37:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dh_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dh_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dh_store` DEFAULT CHARACTER SET utf8 ;
USE `dh_store` ;

-- -----------------------------------------------------
-- Table `dh_store`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_store`.`Producto` (
  `Codigo` INT NOT NULL,
  `Desc_Larga` VARCHAR(95) NULL,
  `Desc_Corta` VARCHAR(45) NULL,
  `Precio` DECIMAL(5,2) NULL,
  `Descuento` DECIMAL(5,2) NULL,
  `Imagen` VARCHAR(300) NULL,
  `Duracion` INT NULL,
  `Fecha` DATETIME NULL,
  `Estado` CHAR(1) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dh_store`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_store`.`Usuario` (
  `Codigo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Usuario` VARCHAR(45) NULL,
  `Contrasena` VARCHAR(45) NULL,
  `Contrasena_Encrip` VARCHAR(45) NULL,
  `Estado` CHAR(1) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dh_store`.`Blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_store`.`Blog` (
  `Codigo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Fecha` DATETIME NULL,
  `Estado` CHAR(1) NULL,
  `Imagen` VARCHAR(300) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dh_store`.`Correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_store`.`Correo` (
  `Codigo` INT NOT NULL,
  `correo` VARCHAR(65) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dh_store`.`Categoria_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh_store`.`Categoria_Producto` (
  `Codigo` INT NOT NULL,
  `Descripcion` VARCHAR(95) NULL,
  `Estado` CHAR(1) NULL,
  `Producto_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Categoria_Producto_Producto_idx` (`Producto_Codigo` ASC),
  CONSTRAINT `fk_Categoria_Producto_Producto`
    FOREIGN KEY (`Producto_Codigo`)
    REFERENCES `dh_store`.`Producto` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
